# Generated by Django 5.2.1 on 2025-06-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioHoldings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_pan', models.CharField(db_index=True, max_length=12)),
                ('portfolio', models.CharField(max_length=50)),
                ('asset_class', models.CharField(max_length=50)),
                ('folio_id', models.CharField(blank=True, max_length=50, null=True)),
                ('folio_name', models.CharField(blank=True, max_length=100, null=True)),
                ('instrument_id', models.CharField(max_length=50)),
                ('instrument_name', models.CharField(max_length=100)),
                ('holding_value', models.FloatField(blank=True, null=True)),
                ('holding_units', models.FloatField(blank=True, null=True)),
                ('holding_price', models.FloatField(blank=True, null=True)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('pl', models.FloatField(blank=True, null=True)),
                ('plp', models.FloatField(blank=True, null=True)),
                ('cagr', models.FloatField(blank=True, null=True)),
                ('xirr', models.FloatField(blank=True, null=True)),
                ('current_price_date', models.DateField(blank=True, null=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'portfolio_holdings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PortfolioTransactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_pan', models.CharField(db_index=True, max_length=12)),
                ('portfolio', models.CharField(max_length=50)),
                ('asset_class', models.CharField(max_length=50)),
                ('folio_id', models.CharField(blank=True, max_length=50, null=True)),
                ('folio_name', models.CharField(blank=True, max_length=100, null=True)),
                ('instrument_id', models.CharField(max_length=50)),
                ('instrument_name', models.CharField(max_length=100)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_type', models.CharField(max_length=20)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('units', models.FloatField(blank=True, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('balance_units', models.FloatField(blank=True, null=True)),
                ('holding_value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'portfolio_transactions',
                'managed': True,
            },
        ),
    ]
