# Generated by Django 5.2.1 on 2025-07-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedIncome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_pan', models.CharField(db_index=True, max_length=12)),
                ('portfolio', models.CharField(max_length=50)),
                ('asset_class', models.CharField(max_length=50)),
                ('instrument_id', models.CharField(max_length=50)),
                ('instrument_name', models.CharField(max_length=100)),
                ('folio_id', models.CharField(blank=True, max_length=50, null=True)),
                ('folio_name', models.CharField(blank=True, max_length=100, null=True)),
                ('invested_amount', models.FloatField(blank=True, null=True)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('compunding_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_investment', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('interest_payout', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'fixed_income',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='portfolioholdings',
            name='goalpot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
