# Generated by Django 5.2.1 on 2025-07-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_fixedincome_portfolioholdings_goalpot'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotransactions',
            name='goalpot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
