# Generated by Django 5.2.1 on 2025-07-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_insurance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='policy_number',
            new_name='policy_no',
        ),
    ]
