# Generated by Django 5.2.1 on 2025-07-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_policy_number_insurance_policy_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='current_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='total_premium_paid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
