# Generated by Django 5.2.1 on 2025-07-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_insurance_current_value_insurance_total_premium_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceTransactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_pan', models.CharField(blank=True, max_length=10, null=True)),
                ('policy_no', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'insurance_transactions',
                'managed': True,
            },
        ),
    ]
