# Generated by Django 5.2.1 on 2025-07-03 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_insurancetransactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurancetransactions',
            old_name='amount',
            new_name='transaction_amount',
        ),
    ]
