# Generated by Django 5.2.1 on 2025-06-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_pan', models.CharField(blank=True, max_length=10, null=True)),
                ('ledger_name', models.CharField(max_length=100, unique=True)),
                ('ledger_type', models.CharField(blank=True, max_length=50, null=True)),
                ('instrument_id', models.CharField(blank=True, max_length=50, null=True)),
                ('folio_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ledger',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LedgerTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ledger_type', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'ledger_types',
                'managed': True,
            },
        ),
    ]
