# Generated by Django 5.2.1 on 2025-06-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentGroups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instrument_group', models.CharField(max_length=50, unique=True)),
                ('instrument_nature', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'instrument_groups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_pan', models.CharField(blank=True, max_length=10, null=True)),
                ('instrument_name', models.CharField(max_length=100, unique=True)),
                ('instrument_id', models.CharField(blank=True, max_length=50, null=True)),
                ('instrument_group', models.CharField(blank=True, max_length=50, null=True)),
                ('folio_number', models.CharField(blank=True, max_length=50, null=True)),
                ('folio_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'instruments',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
        migrations.DeleteModel(
            name='LedgerTypes',
        ),
    ]
