# Generated by Django 5.2.1 on 2025-06-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_instrumentgroups_instruments_delete_ledger_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruments',
            old_name='folio_number',
            new_name='folio_no',
        ),
    ]
