# Generated by Django 5.2.1 on 2025-06-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_rename_folio_number_instruments_folio_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstrumentGroups',
            new_name='LedgerGroups',
        ),
        migrations.RenameModel(
            old_name='Instruments',
            new_name='LedgerMaster',
        ),
        migrations.RenameField(
            model_name='ledgergroups',
            old_name='instrument_group',
            new_name='ledger_group',
        ),
        migrations.RenameField(
            model_name='ledgergroups',
            old_name='instrument_nature',
            new_name='ledger_nature',
        ),
        migrations.RenameField(
            model_name='ledgermaster',
            old_name='instrument_group',
            new_name='ledger_group',
        ),
        migrations.RenameField(
            model_name='ledgermaster',
            old_name='instrument_id',
            new_name='ledger_id',
        ),
        migrations.RenameField(
            model_name='ledgermaster',
            old_name='instrument_name',
            new_name='ledger_name',
        ),
        migrations.AlterModelTable(
            name='ledgergroups',
            table='ledger_groups',
        ),
        migrations.AlterModelTable(
            name='ledgermaster',
            table='ledger_master',
        ),
    ]
