# Generated by Django 5.2.1 on 2025-06-26 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_rename_instrumentgroups_ledgergroups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgermaster',
            old_name='ledger_id',
            new_name='ledger_ref_no',
        ),
    ]
