# Generated by Django 5.2.1 on 2025-06-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_rename_ledger_id_ledgermaster_ledger_ref_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_pan', models.CharField(blank=True, max_length=10, null=True)),
                ('insurance_policy_name', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_date_of_commencement', models.DateField(blank=True, null=True)),
                ('insurance_date_of_last_premium', models.DateField(blank=True, null=True)),
                ('insurance_date_of_maturity', models.DateField(blank=True, null=True)),
                ('insurance_premium_amount', models.FloatField(blank=True, null=True)),
                ('insurance_sum_assured', models.FloatField(blank=True, null=True)),
                ('insurance_premium_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_agent_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'insurance_master',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='ledgermaster',
            name='folio_name',
        ),
        migrations.RemoveField(
            model_name='ledgermaster',
            name='folio_no',
        ),
    ]
