# Generated by Django 5.2.1 on 2025-07-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_insurancemaster_remove_ledgermaster_folio_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsuranceMaster',
        ),
    ]
