# Generated by Django 5.2.1 on 2025-06-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundsEod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('scheme_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('scheme_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('amc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('isin', models.CharField(blank=True, max_length=20, null=True)),
                ('nav', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mutualfunds_eod',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MutualFundsHistorical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('scheme_code', models.CharField(blank=True, max_length=20, null=True)),
                ('isin', models.CharField(blank=True, max_length=20, null=True)),
                ('scheme_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nav', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mutualfunds_historical',
                'managed': True,
                'unique_together': {('scheme_code', 'date')},
            },
        ),
    ]
