# Generated by Django 5.2.1 on 2025-06-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSEEodHistorical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('last', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nse_historical',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NSEEod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trade_date', models.DateField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('prev_close', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nse_eod',
                'managed': True,
                'unique_together': {('symbol', 'trade_date')},
            },
        ),
    ]
