# Generated by Django 5.2.1 on 2025-07-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_nseeodhistorical_nseeod'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfundseod',
            name='asset_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundseod',
            name='scheme_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
