# Generated by Django 5.2.1 on 2025-06-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_pan', models.CharField(blank=True, max_length=10, null=True)),
                ('ledger_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ledger_group', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_no', models.CharField(blank=True, max_length=50, null=True)),
                ('debit', models.FloatField(blank=True, null=True)),
                ('credit', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bank_statement',
                'managed': True,
            },
        ),
    ]
