# Generated by Django 5.2.1 on 2025-06-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankstatement',
            old_name='ledger_name',
            new_name='bank_ledger_name',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='ledger_group',
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='brs_ledger_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
